### ISSUE TITLE
base.html is hardcoded to english language

### ISSUE THREAD

**Issue by solbu** [wamonite/relapse#2]
Hi.
I was trying to validate a new site for our team, and was checking it against w3c.org's validator, and discovered that the template is hardcoding the content as being english. We write in norwegian, and the validator detected this, and reported it as an error that the content language is different that the claimed language.

The base.html currently have: `<html lang="en">`
The correct way is: `<html lang="{{ DEFAULT_LANG }}">`

This way it will populate the claimed language by the configuration file 
variable «`DEFAULT_LANG = u'XX'`».

**Comment by wamonite** [comment]
Thanks for taking the time to submit this issue.
